// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * Log
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "Log": (arg1) => {
        return window.go.main.App.Log(arg1);
      },
      /**
       * ReportFile
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<void>} 
       */
      "ReportFile": (arg1, arg2) => {
        return window.go.main.App.ReportFile(arg1, arg2);
      },
      /**
       * ReportPath
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "ReportPath": (arg1) => {
        return window.go.main.App.ReportPath(arg1);
      },
    },
  },

};
export default go;
